=pod

=head1 NAME

Devel::OverrideGlobalRequire - Override CORE::GLOBAL::require safely

=head1 VERSION

version 0.001

=head1 SYNOPSIS

  use Devel::OverrideGlobalRequire;

  override_global_require( sub { ... } );

=head1 DESCRIPTION

This module overrides C<CORE::GLOBAL::require> with a code reference in a way
that plays nice with any existing overloading and ensures the right calling
package is in scope.

=for Pod::Coverage override_global_require
TRACE

=for :stopwords cpan testmatrix url annocpan anno bugtracker rt cpants kwalitee diff irc mailto metadata placeholders metacpan

=head1 SUPPORT

=head2 Bugs / Feature Requests

Please report any bugs or feature requests through the issue tracker
at L<https://rt.cpan.org/Public/Dist/Display.html?Name=Devel-OverrideGlobalRequire>.
You will be notified automatically of any progress on your issue.

=head2 Source Code

This is open source software.  The code repository is available for
public review and contribution under the terms of the license.

L<http://git.shadowcat.co.uk/gitweb/gitweb.cgi?p=p5sagit/Devel-OverrideGlobalRequire.git;a=summary>

  git clone git://git.shadowcat.co.uk/p5sagit/Devel-OverrideGlobalRequire.git

=head1 AUTHORS

=over 4

=item *

Peter Rabbitson <ribasushi@cpan.org>

=item *

Andrew Main <zefram@cpan.org>

=item *

David Golden <dagolden@cpan.org>

=back

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Peter Rabbitson.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

